initial_lulc:
  enabled: true
  stressor_lulc_107_2017:
    decline_type: exp_decline
    exp_decline:
      lambda_decay: 500
    prop_decline:
      k_value: 500
    types: null
  stressor_lulc_7_2017:
    decline_type: exp_decline
    exp_decline:
      lambda_decay: 500
    prop_decline:
      k_value: 500
    types: null
vector:
  enabled: true
  railways:
    decline_type: exp_decline
    exp_decline:
      lambda_decay: 500
    prop_decline:
      k_value: 500
    types: null
  roads:
    motorway:
      decline_type: exp_decline
      exp_decline:
        lambda_decay: 500
      prop_decline:
        k_value: 500
      types: null
    primary:
      decline_type: exp_decline
      exp_decline:
        lambda_decay: 500
      prop_decline:
        k_value: 500
      types: null
    secondary:
      decline_type: exp_decline
      exp_decline:
        lambda_decay: 500
      prop_decline:
        k_value: 500
      types: null
    tertiary:
      decline_type: exp_decline
      exp_decline:
        lambda_decay: 500
      prop_decline:
        k_value: 500
      types: null
    trunk:
      decline_type: exp_decline
      exp_decline:
        lambda_decay: 500
      prop_decline:
        k_value: 500
      types: null
    types: true
  types: true
