initial_lulc:
  enabled: true
  stressor_lulc_5:
    decline_type: exp_decline
    exp_decline:
      lambda_decay: 130
    prop_decline:
      k_value: 8
    types: null
  stressor_lulc_6:
    decline_type: exp_decline
    exp_decline:
      lambda_decay: 110
    prop_decline:
      k_value: 7
    types: null
  stressor_lulc_7:
    decline_type: exp_decline
    exp_decline:
      lambda_decay: 150
    prop_decline:
      k_value: 9
    types: null
vector:
  enabled: true
  railways:
    decline_type: exp_decline
    exp_decline:
      lambda_decay: 200
    prop_decline:
      k_value: 100
    types: null
  roads:
    motorway:
      decline_type: exp_decline
      exp_decline:
        lambda_decay: 50
      prop_decline:
        k_value: 5
      types: null
    primary:
      decline_type: exp_decline
      exp_decline:
        lambda_decay: 70
      prop_decline:
        k_value: 6
      types: null
    secondary:
      decline_type: exp_decline
      exp_decline:
        lambda_decay: 90
      prop_decline:
        k_value: 7
      types: null
    tertiary:
      decline_type: exp_decline
      exp_decline:
        lambda_decay: 130
      prop_decline:
        k_value: 9
      types: null
    trunk:
      decline_type: exp_decline
      exp_decline:
        lambda_decay: 50
      prop_decline:
        k_value: 5
      types: null
    types: true
  types: true
