# !DO NOT REMOVE keys, just assign 'null' if needed

## INPUT DATASETS

# land-use/land-cover (GeoTIFF)
lulc: 'lulc_albera_ext_{year}.tif'
# yearstamp of raster dataset to be enriched with vector data
year: 2017
# LULC codes of corresponding vector data (all parameters are optional)
lulc_codes:
    lulc_road: 4 # corresponding LULC code ('built area')
    lulc_railway: 4 
    lulc_water: 2 

# flag to create impedance dataset from reclassification table
create_impedance: true # 'true' if the impedance dataset is not provided (create based on reclassification table), 'false'(impedance provided)
# landscape impedance based on LULC dataset (auxiliary GeoTIFFs)
impedance_tif: 'impedance_lulc_albera_ext_{year}.tif'  # added 'impedance_' prefix
# input auxiliary csv data (reclassification table)
impedance: 'reclass_ext.csv' # to fetch table with LULC types mapping with impedance values

# vector data
osm_data: 'osm_merged_{year}.gpkg' # derived from Open Street Map
user_vector: null # derived from other sources and provided by users ('null' by default)

## PATHS TO DIRECTORIES
# recommended to leave as default
input_dir: 'data/input'
lulc_dir: 'data/input/lulc'
vector_dir: 'data/input/vector'
impedance_dir: 'data/input/impedance'
output_dir: 'data/output'

## 1st NOTEBOOK
# Protected Planet API
token: "your_token" # replace with your token
historic_data: true # 'true' by default if user wants to filter protected areas by the year of status. Warning: some of the protected areas can lack the status year
marine: false # 'false' by default to bring marine protected areas or not. warning: being transformed into 'False' in URI, but recognised as a boolean value. Does not cause issues.
api_countries: true # 'true' by default. Brings codes of countries intersecting with input raster dataset. Otherwise, user must specify list of countries as ISO3 codes.
# Parameters to update the impedance datasets
lulc_reclass_table: false # 'false' (use the effect of protected areas) or 'true' (use the reclassification table)
pa_effect: 0.3 # positive effect of protected areas on landscape impedance (for example, if landscape impedance of non-protected grasslands is 10, it will be 3 for protected grasslands)

## 2nd NOTEBOOK

# OSM buffering (might be any value, but integer is recommended)
width_lev1: 30 # roads: 'motorway', 'motorway_link', 'trunk', 'trunk_link'
width_lev2: 20 # roads: 'primary', 'primary_link', 'secondary', 'secondary_link'
width_other: 10 # other roads and other layers (railways)

## 3rd NOTEBOOK
# matching OSM categories with LULC types
user_matching: 'true' # 'true' by default. 'false' triggers text-matching subtool searching over the definitions of LULC types